version: "3.7"

services:
  web:
    build:
      context: .
      args:
        JAVA_OPTS: ${JAVA_OPTS:-="-Xms1G -Xmx2G -Dfile.encoding=UTF-8"}
      target: app
    ports:
      - "5858:5858"
    tty: true
    stdin_open: true
    depends_on: 
      - db
      
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EHR
      - PGPORT=${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
