version: "3.7"
services:
  web:
    build:
      context: .
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        JAVA_OPTS: ${JAVA_OPTS}
      target: app
    ports:
      - "5858:5858"
    tty: true
    stdin_open: true
    depends_on: 
      - db
  db:
    #image: "postgres" 
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EHR
    ports:
      - "5432:5432"
#    volumes:
#       - db_data:/var/lib/postgresql/data/
