version: "3.9"

services:
  web:
    build:
      context: .
      target: app
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "5858:5858"
    tty: true
    stdin_open: true
    volumes:
      - "./carnival-micronaut-home/export:/opt/carnival-micronaut/carnival-micronaut-home/export"
      #- ./carnival-micronaut-home/export:/opt/carnival-micronaut/build/export
    depends_on: 
      db:
        condition: service_healthy
      
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "EHR"]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EHR
      - PGPORT=${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
