# 1.
# Edit .env-template and save as .env

# 2.
# Checkout carnival-micronaut-home into this directory
# .../carnival-micronaut
# .../carnival-micronaut/carnival-micronaut-home

# git clone git@github.com:pmbb-ibi/carnival-micronaut-home.git
# OR
# git clone https://github.com/pmbb-ibi/carnival-micronaut-home.git

# TODO? Change above so uses host's environment variables which point at carnival-micronaut-home,
#       instead of having it hardcoded 

# 3.
# sudo docker-compose build

# 4.
# sudo docker-compose up

version: "3.7"
services:
  web:
    build:
      context: .
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        JAVA_OPTS: ${JAVA_OPTS}
      target: app
    ports:
      - "5858:5858"

    tty: true
    stdin_open: true

#    command: "env"
#    command: java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -Dcarnival.home=/opt/carnival-micronaut-home -Dlogback.configurationFile=/opt/carnival-micronaut-home/config/logback.xml -Dmicronaut.config.files=/opt/carnival-micronaut-home/config/application.yml -jar /opt/carnival-micronaut/build/libs/carnival-micronaut-0.1-all.jar
#    command: 
#java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} 
#-Dcarnival.home=/opt/carnival-micronaut-home 
#-Dlogback.configurationFile=/opt/carnival-micronaut-home/config/logback.xml 
#-Dmicronaut.config.files=/opt/carnival-micronaut-home/config/application.yml 
#-jar /opt/carnival-micronaut/build/libs/carnival-micronaut-0.1-all.jar

