version: "3.7"
services:
  web:
    build:
      context: .
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        JAVA_OPTS: ${JAVA_OPTS}
      target: app
    ports:
      - "5858:5858"

    tty: true
    stdin_open: true
