version: "3.7"


# mounted volume is used so that when code changes, 
# tests can be rerun without needing to rebuild

services:
  tester:
    build:
      context: .
      target: base
      args:
        JAVA_OPTS: ${JAVA_OPTS:-="-Xms1G -Xmx2G -Dfile.encoding=UTF-8"}
    command: "gradle run --no-daemon"
    tty: true
    stdin_open: true
    
    volumes:
      - "./src:/opt/carnival-micronaut/src:ro"

    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EHR
      - PGPORT=${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
