carnival-micronaut:

  name: CarnivalMicronaut

  example-db:
    server: db
#    server: localhost
    port: 5433
    user: postgres
    password: postgres
    databaseName: EHR

  graph:
    runtime: tinker # neo4j tinker
    test: tinker 

carnival:

  cache-mode: IGNORE #OPTIONAL

  directories:
    data:
    # root: /Users/yourname/dev/carnival.data
    # graph: /Users/yourname/dev/carnival.data.graph
    # cache: /Users/yourname/dev/carnival.data.cache
    execution:
      # target: /Users/yourname/dev/target

  gremlin:
    neo4j:
      conf:
        dbms:
          directories:
            plugins: /path/to/your/neo4j/plugin/dir
          security:
            auth_enabled: "false"
            procedures:
              unrestricted: apoc.*
              whitelist: apoc.*
