name: Docker CI

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - master

env:
  PGPORT: 5433

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose-test.yml build
      
    - name: Run integration tests
      run: |
        docker compose -f docker-compose-test.yml up --abort-on-container-exit
